### PR TITLE
Initial integration of download from cmake, add cpack config file

### PR DESCRIPTION
**Pull request by xor-gate**
This is WIP, hopefully finish in the upcoming week.

### CODE REVIEW

**Comment by ludocode** [comment]
Discussed in issue #1. I'd like to avoid downloading dependencies with CMake. I want to keep the release packages as standalone, including pre-downloaded libraries and pre-generated manpages so as to have as few external dependencies as possible (currently only CMake itself.) The `fetch.sh` script to download packages really only exists as a convenience for developers wanting to contribute changes to msgpack-tools. Downloading external packages should not be considered part of the "normal" build or install process.

**Comment by xor-gate** [comment]
Yeah you are right, but there is no difference in convenience with `fetch.sh` vs `CMake downloader`. I'm used to this flow because the "normal" build/install process at my work is exactly the same as the release process. We provide development,testing,acceptation and production package straight from git tags and branches with our CI. I have no real idea how you would like some sort of mechanism into `msgpack-tools` as also other people could benefit from it. 

I totaly understand it takes way to much time to support distro X,Y,Z and platform A,B,C.

We could also keep this as a reference and close as-is. Then I will fork the latest release and integrate my changes as needed at Dual Inventive organisation and feature-branch. So our effort will not be lost-in-battle.

Let me know what you think.

**Comment by xor-gate** [comment]
I will close this, as this will be solved for the project in a different way.

**Comment by ludocode** [comment]
Having thought this over, I think you're right that CMake should handle fetching dependencies and generating man pages. The build process should not be so different between the repository and release packages, and the half-baked shell scripts for doing these things need to go.

I'm looking at building off of this PR and adding the ability to generate man pages if md2man-roff is installed, this way I can get rid of `tools/fetch.sh` and `tools/man.sh`. Right now the code doesn't build on Arch (`${CMAKE_SYSTEM_VARIANT}` is missing quotes around it) but I'll fix that as well. I'd like to preserve your code to build of a .deb package if possible so I'm getting a Debian VM set up right now to see if I can make it work.

**Comment by xor-gate** [comment]
I use CMake in production environment where every build results in a debian package and is automaticly pushed and pgp-signed and added to out own repository. So when you develop and release it automaticly results in good packages :+).

**Pull request closed without merging**
